name: Run tests

on: 
  pull_request:
      branches: [ "main" ]
      types: [opened, synchronize, reopened, ready_for_review]      
  workflow_dispatch:
jobs:
  run_tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          echo "hello mirek"
          
